use crate::ui::state::MatchupType;

#[derive(Debug, Clone)]
pub enum Message {
    ShowIngest(bool),
    UpdateIngest(String),
    SubmitIngest,
    SetChangePlayerName(Option<(Option<String>, String)>),
    ChangePlayerSubmit,
    ShowConfig(bool),
    UpdateScoreStartingElo(String),
    UpdateScoreGamePoints(String),
    UpdateScoreEloPow(String),
    UpdateScoreWrPow(String),
    UpdateScoreEloWeight(String),
    UpdateScoreWrWeight(String),

    UpdateMatchWeightLeastPlayed(String),
    UpdateMatchWeightNemesis(String),
    UpdateMatchWeightNeighbor(String),
    UpdateMatchWeightWrNeighbor(String),
    UpdateMatchWeightLostWith(String),
    SaveConfig,
    SelectPlayer(usize, Option<String>),
    SelectPlayers([String; 4]),
    AddPlayerToNextSlot(String),
    SelectWinner(String),
    SelectMatchPlayer(String),
    DeletePlayer(String),
    SubmitGame,
    ClearGame,
    Reload,
    CloseError,
    Load(String),
    Save(String),
    New,
    SetMatchupType(MatchupType),
    ShowGames(bool),
    OpenChangeWinnerModal(usize),
    ChangeGameWinner(usize, String),
    DeleteGame(usize),
}
