[package]
name = "app"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "commander-tournament"
path = "src/main.rs"

[features]
default = ["serde_json", "serde_toml"]

dev = ["dep:tempfile", "default"]
serde_json = ["dep:serde_json"]
serde_toml = ["dep:toml"]


[dependencies]
anyhow = "1.0.100"
appconfig = "0.2.1"
async-fs = "2.2.0"
iced = { version = "0.14.0", features = ["tokio"] }
itertools = "0.14.0"
opener = "0.8.4"
rfd = "0.17.2"
serde = { version = "1.0.228" }
ron = "0.12.1"
serde_json = { version = "1.0.150", optional = true }
toml = { version = "1.1.2", optional = true }
thiserror = "2.0.18"
edh_tourn = { path = "../edh_tourn/" }
directories = "6.0.0"
iced_aw = { version = "0.14.1" }
nerd-font-symbols = "0.3.0"
derive_more = { version = "2", features = ["from", "display"] }
iced_futures = "0.14.0"
tempfile = { version = "3.27.0", optional = true }
tokio = { version = "1.52.3", features = ["rt", "macros"] }
auto-const-array = "0.2.2"
paste = "1.0.15"
im = "15.1.0"

[dev-dependencies]
app = { path = ".", features = ["dev"] }
edh_tourn = { path = "../edh_tourn/", features = ["dev"] }
approx = "0.5.1"
iced_test = "0.14.0"

[lints]
workspace = true
