[package]
name = "edh_tourn"
version = "0.1.0"
edition = "2024"

[features]
dev = ["dep:rand", "dep:rand_chacha"]

[dependencies]
anyhow = "1.0.100"
itertools = "0.15.0"
serde = {version="1.0.228", features=["derive"]}
thiserror = "2.0.18"
ron = "0.12.1"
rand = {version = "0.10.1", optional=true}
rand_chacha = {version="0.10.0", optional=true}
derive_more = {version = "2", features = ["from", "constructor", "display"]}
auto-const-array = "0.2.2"

[dev-dependencies]
edh_tourn = {path=".", features=["dev"]}
toml = "1.1.2"
serde_json = "1.0.150"
approx = "0.5.1"

[lints]
workspace = true
