name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v7
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        components: clippy, rustfmt
    - name: Install Clippy-Sarif
      uses: baptiste0928/cargo-install@v3
      with:
        crate: clippy-sarif
    - name: Install Sarif-fmt
      uses: baptiste0928/cargo-install@v3
      with:
        crate: sarif-fmt
    - name: Run Clippy
      run: cargo clippy --all --no-deps --all-features --message-format=json -- -W clippy::todo | sort | uniq | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
      continue-on-error: true
    - name: Upload analysis results to GitHub
      uses: github/codeql-action/upload-sarif@v4
      with:
        sarif_file: rust-clippy-results.sarif
        wait-for-processing: true
    - name: Check Formatting
      uses: actions-rust-lang/rustfmt@v1

  coverage:
    name: Test Coverage
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-A warnings"
    strategy:
      fail-fast: false
      matrix:
        package: [edh_tourn, app]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v7
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        components: llvm-tools
        cache-key: ${{ matrix.package }}
    - name: Install Cargo LLVM Cov
      uses: baptiste0928/cargo-install@v3
      with:
        crate: cargo-llvm-cov
    - name: Generate Coverage Output
      run: cargo llvm-cov test -p ${{ matrix.package }} --no-fail-fast --all-features --lcov --output-path lcov_raw.info
    - name: Prepare Coverage Outputs
      run: cp lcov_raw.info lcov-${{ matrix.package }}.info
    - name: Upload LCOV Artifact
      uses: actions/upload-artifact@v7
      with:
        name: lcov-${{ matrix.package }}
        path: lcov-${{ matrix.package }}.info
        retention-days: 1
    - name: Filter and Format Coverages
      run: chmod +x .github/workflows/coverages.bash && .github/workflows/coverages.bash
    - name: Print to Job Summary
      uses: livewing/lcov-job-summary@v1.3.0
      with:
        lcov: lcov.info

  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, windows-11-arm]
    runs-on: ${{matrix.os}}
    env:
      RUSTFLAGS: "-A warnings"
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v7
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
    - name: Run tests
      run: cargo test --all --verbose
    - name: Build
      run: cargo build --all --verbose --release
